security:
  password_hashers:
    App\Entity\User:
      algorithm: bcrypt
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: emailAddress
    users_in_memory: { memory: null }
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      login_throttling:
        max_attempts: 4
      logout:
        path: logout
        target: home
      custom_authenticator: App\Security\AppAuthenticator

  role_hierarchy:
    ROLE_admin: ROLE_user

  access_control:
    - { path: ^/admin/, roles: ROLE_admin }
    - { path: ^/blog/, roles: ROLE_user }
    - { path: ^/user/, roles: ROLE_user }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
